name = "infinitydoc-ssr"
main = "worker.js"
compatibility_date = "2024-11-18"

assets = { directory = ".", binding = "ASSETS", html_handling = "force-trailing-slash", not_found_handling = "404-page" }
