name = "infinitydoc-next"
main = "worker.js"
compatibility_date = "2024-11-18"

assets = { directory = "./public", binding = "ASSETS", html_handling = "force-trailing-slash", not_found_handling = "404-page" }

d1_databases = [
  { binding = "DB", database_name = "infinitydoc-prod", database_id = "infdoc-prod" },
]
