name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    env:
      DENOMON_WORKSPACE_DIR: ${{ github.workspace }}
      DENOMON_ARTIFACTS_DIR: ${{ github.workspace }}/.denomon/artifacts
      DENOMON_KITS_FILE: ${{ github.workspace }}/.denomon/kits.json
      DENOMON_KITS_DIR: ${{ github.workspace }}/.denomon/kits

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: 1.x
      
      - name: Compile Denomon CLI
        run: deno task compile-cli

      - name: Build Web
        run: .denomon/bin/denomon build web

      - name: Build Worker
        run: .denomon/bin/denomon build worker

      - name: Prepare artifacts
        run: |
          mkdir -p upload
          mv .denomon/artifacts/worker/main.js upload/worker.js
          mkdir -p upload/public
          mv .denomon/artifacts/web/* upload/public
          cp ship/web/wrangler.toml upload
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: upload
